version: "3.8"
services:
  backend:
    image: 904233131614.dkr.ecr.us-east-1.amazonaws.com/ocms:backend-latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5000
    networks:
      - ocms-network
    volumes:
      - /var/app/uploads:/app/uploads
  frontend:
    image: 904233131614.dkr.ecr.us-east-1.amazonaws.com/ocms:frontend-latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ocms-network
networks:
  ocms-network:
    driver: bridge
